<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://webservices.portal.fidc.fromtis.com.br/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://webservices.portal.fidc.fromtis.com.br/" name="RequisicaoCertificacaoDigital">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://webservices.portal.fidc.fromtis.com.br/" schemaLocation="https://portalfidc4.singulare.com.br:443/portal/requisicaoCertificacaoDigital?xsd=1"/>
        </xsd:schema>
    </types>
    <message name="requisicao">
        <part name="parameters" element="tns:requisicao"/>
    </message>
    <portType name="RequisicaoCertificacaoDigital">
        <operation name="requisicao">
            <input wsam:Action="http://webservices.portal.fidc.fromtis.com.br/RequisicaoCertificacaoDigital/requisicao" message="tns:requisicao"/>
        </operation>
    </portType>
    <binding name="RequisicaoCertificacaoDigitalPortBinding" type="tns:RequisicaoCertificacaoDigital">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="requisicao">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
        </operation>
    </binding>
    <service name="RequisicaoCertificacaoDigital">
        <port name="RequisicaoCertificacaoDigitalPort" binding="tns:RequisicaoCertificacaoDigitalPortBinding">
            <soap:address location="http://localhost:8080/fromtis/ws/requisicaoCertificacaoDigital"/>
        </port>
    </service>
</definitions>
